image: gcc:11.4

stages:
  - prep
  - build
  - test

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

prep:
  stage: prep
  before_script:
    - apt-get update
    - apt-get -y install libcriterion-dev ninja-build cmake

build:
  stage: build
  script:
    - mkdir build/ && cd build/
    - cmake -G Ninja ..
    - ninja

